spring.application.name=category-service

spring.datasource.url=jdbc:postgresql://localhost:5432/categorydb
spring.datasource.username=user
spring.datasource.password=user123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
config.value=category-service,we are in dev after change
server.port=9091
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.refresh.enable=false

#RabbitMq configuratio
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#encrypt key 


#bus endpoint 
management.endpoints.web.exposure.include=busrefresh
