spring:
  application:
    name: quiz-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: quizdb
      

  # rabbitmq:
  #   host: localhost
  #   port: 5672
  #   username: guest
  #   password: guest

  cloud:
    function:
      definition: getQuizBinding
    stream:
      kafka:
        binder:
          brokers: localhost:9098
      bindings:

        # OUTPUT
        quizCreatedBinding-out-0:
          destination: quiz-created

        # INPUT
        getQuizBinding-in-0:
          destination: questions-generated
          group: ${spring.application.name}
          content-type: text/plain

  config:
    value: "quiz-service,we are in dev after change"

server:
  port: 9092

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true
    refresh:
      enable: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
